version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.1
    - 1.8.1
    - 1.9.0
    - 1.9.1
  - dependency-name: bootsnap
    versions:
    - 1.6.0
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
  - dependency-name: rubocop-performance
    versions:
    - 1.10.0
    - 1.10.1
    - 1.9.2
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: timecop
    versions:
    - 0.9.3
    - 0.9.4
  - dependency-name: carrierwave
    versions:
    - 2.1.1
  - dependency-name: database_cleaner
    versions:
    - 2.0.0
    - 2.0.1
  - dependency-name: rubocop-rspec
    versions:
    - 2.2.0
  - dependency-name: capybara
    versions:
    - 3.35.1
    - 3.35.3
  - dependency-name: nokogiri
    versions:
    - 1.11.0
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
    - 10.7.1
  - dependency-name: picnic
    versions:
    - 6.5.5
  - dependency-name: react-dom
    versions:
    - 17.0.1
    - 17.0.1
  - dependency-name: react
    versions:
    - 17.0.1
    - 17.0.1
  - dependency-name: jquery
    versions:
    - 3.6.0
  - dependency-name: bootbox
    versions:
    - 5.5.2
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: throttle-debounce
    versions:
    - 3.0.1
