import highlight from 'highlight.js/lib/core';

import asciidoc from 'highlight.js/lib/languages/asciidoc';
import bash from 'highlight.js/lib/languages/bash';
import basic from 'highlight.js/lib/languages/basic';
import clean from 'highlight.js/lib/languages/clean';
import clojure from 'highlight.js/lib/languages/clojure';
import cmake from 'highlight.js/lib/languages/cmake';
import coffeescript from 'highlight.js/lib/languages/coffeescript';
import cpp from 'highlight.js/lib/languages/cpp';
import crystal from 'highlight.js/lib/languages/crystal';
import csharp from 'highlight.js/lib/languages/csharp';
import css from 'highlight.js/lib/languages/css';
import d from 'highlight.js/lib/languages/d';
import dart from 'highlight.js/lib/languages/dart';
import diff from 'highlight.js/lib/languages/diff';
import dockerfile from 'highlight.js/lib/languages/dockerfile';
import ebnf from 'highlight.js/lib/languages/ebnf';
import elixir from 'highlight.js/lib/languages/elixir';
import elm from 'highlight.js/lib/languages/elm';
import erb from 'highlight.js/lib/languages/erb';
import erlang from 'highlight.js/lib/languages/erlang';
import fsharp from 'highlight.js/lib/languages/fsharp';
import gherkin from 'highlight.js/lib/languages/gherkin';
import go from 'highlight.js/lib/languages/go';
import gradle from 'highlight.js/lib/languages/gradle';
import groovy from 'highlight.js/lib/languages/groovy';
import haml from 'highlight.js/lib/languages/haml';
import handlebars from 'highlight.js/lib/languages/handlebars';
import http from 'highlight.js/lib/languages/http';
import ini from 'highlight.js/lib/languages/ini';
import java from 'highlight.js/lib/languages/java';
import javascript from 'highlight.js/lib/languages/javascript';
import json from 'highlight.js/lib/languages/json';
import kotlin from 'highlight.js/lib/languages/kotlin';
import less from 'highlight.js/lib/languages/less';
import lisp from 'highlight.js/lib/languages/lisp';
import llvm from 'highlight.js/lib/languages/llvm';
import makefile from 'highlight.js/lib/languages/makefile';
import markdown from 'highlight.js/lib/languages/markdown';
import mathematica from 'highlight.js/lib/languages/mathematica';
import matlab from 'highlight.js/lib/languages/matlab';
import nginx from 'highlight.js/lib/languages/nginx';
import objectivec from 'highlight.js/lib/languages/objectivec';
import perl from 'highlight.js/lib/languages/perl';
import pgsql from 'highlight.js/lib/languages/pgsql';
import php from 'highlight.js/lib/languages/php';
import plaintext from 'highlight.js/lib/languages/plaintext';
import powershell from 'highlight.js/lib/languages/powershell';
import prolog from 'highlight.js/lib/languages/prolog';
import properties from 'highlight.js/lib/languages/properties';
import python from 'highlight.js/lib/languages/python';
import r from 'highlight.js/lib/languages/r';
import ruby from 'highlight.js/lib/languages/ruby';
import rust from 'highlight.js/lib/languages/rust';
import scala from 'highlight.js/lib/languages/scala';
import scss from 'highlight.js/lib/languages/scss';
import shell from 'highlight.js/lib/languages/shell';
import sql from 'highlight.js/lib/languages/sql';
import stylus from 'highlight.js/lib/languages/stylus';
import swift from 'highlight.js/lib/languages/swift';
import latex from 'highlight.js/lib/languages/latex';
import typescript from 'highlight.js/lib/languages/typescript';
import vim from 'highlight.js/lib/languages/vim';
import xml from 'highlight.js/lib/languages/xml';
import yaml from 'highlight.js/lib/languages/yaml';

import 'highlight.js/styles/base16/railscasts.css';

highlight.registerLanguage('asciidoc', asciidoc);
highlight.registerLanguage('bash', bash);
highlight.registerLanguage('basic', basic);
highlight.registerLanguage('clean', clean);
highlight.registerLanguage('clojure', clojure);
highlight.registerLanguage('cmake', cmake);
highlight.registerLanguage('coffeescript', coffeescript);
highlight.registerLanguage('cpp', cpp);
highlight.registerLanguage('crystal', crystal);
highlight.registerLanguage('csharp', csharp);
highlight.registerLanguage('css', css);
highlight.registerLanguage('d', d);
highlight.registerLanguage('dart', dart);
highlight.registerLanguage('diff', diff);
highlight.registerLanguage('dockerfile', dockerfile);
highlight.registerLanguage('ebnf', ebnf);
highlight.registerLanguage('elixir', elixir);
highlight.registerLanguage('elm', elm);
highlight.registerLanguage('erb', erb);
highlight.registerLanguage('erlang', erlang);
highlight.registerLanguage('fsharp', fsharp);
highlight.registerLanguage('gherkin', gherkin);
highlight.registerLanguage('go', go);
highlight.registerLanguage('gradle', gradle);
highlight.registerLanguage('groovy', groovy);
highlight.registerLanguage('haml', haml);
highlight.registerLanguage('handlebars', handlebars);
highlight.registerLanguage('http', http);
highlight.registerLanguage('ini', ini);
highlight.registerLanguage('java', java);
highlight.registerLanguage('javascript', javascript);
highlight.registerLanguage('json', json);
highlight.registerLanguage('kotlin', kotlin);
highlight.registerLanguage('less', less);
highlight.registerLanguage('lisp', lisp);
highlight.registerLanguage('llvm', llvm);
highlight.registerLanguage('makefile', makefile);
highlight.registerLanguage('markdown', markdown);
highlight.registerLanguage('mathematica', mathematica);
highlight.registerLanguage('matlab', matlab);
highlight.registerLanguage('nginx', nginx);
highlight.registerLanguage('objectivec', objectivec);
highlight.registerLanguage('perl', perl);
highlight.registerLanguage('pgsql', pgsql);
highlight.registerLanguage('php', php);
highlight.registerLanguage('plaintext', plaintext);
highlight.registerLanguage('powershell', powershell);
highlight.registerLanguage('prolog', prolog);
highlight.registerLanguage('properties', properties);
highlight.registerLanguage('python', python);
highlight.registerLanguage('r', r);
highlight.registerLanguage('ruby', ruby);
highlight.registerLanguage('rust', rust);
highlight.registerLanguage('scala', scala);
highlight.registerLanguage('scss', scss);
highlight.registerLanguage('shell', shell);
highlight.registerLanguage('sql', sql);
highlight.registerLanguage('stylus', stylus);
highlight.registerLanguage('swift', swift);
highlight.registerLanguage('latex', latex);
highlight.registerLanguage('typescript', typescript);
highlight.registerLanguage('vim', vim);
highlight.registerLanguage('xml', xml);
highlight.registerLanguage('yaml', yaml);

window.hljs = highlight;
