require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

AllCops:
  Exclude:
    - 'node_modules/**/*'
    - 'client/node_modules/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - '.git/**/*'
    - 'db/schema.rb'
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/FetchEnvVar:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'config/**/*'
    - 'spec/**/*'

Rails/LexicallyScopedActionFilter:
  Enabled: false

RSpec/RepeatedExample:
  Exclude:
    - 'spec/policies/**/*'

RSpec/RepeatedDescription:
  Exclude:
    - 'spec/policies/**/*'

RSpec/ContextWording:
  Exclude:
    - 'spec/policies/**/*'
  Prefixes:
    - as
    - when
    - with
    - without

# describing a feature spec without `type: :feature` doesn't work
RSpec/DescribeClass:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Capybara/ClickLinkOrButtonStyle:
  Enabled: false

Capybara/RSpec/HaveSelector:
  Enabled: false
