default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0
  <% if ENV['PGUSER'].present? %>
  username: <%= ENV['PGUSER'] %>
  <% end %>
  <% if ENV['PGPASSWORD'].present? %>
  password: <%= ENV['PGPASSWORD'] %>
  <% end %>
  <% if ENV['PGHOST'].present? %>
  host: <%= ENV['PGHOST'] %>
  <% end %>
  <% if ENV['PGPORT'].present? %>
  port: <%= ENV['PGPORT'] %>
  <% end %>

development: &development
  <<: *default
  database: mykonote_development

test:
  <<: *default
  database: mykonote_test

production:
  <<: *default
  database: rails_production
  username: app

local_production:
  <<: *development
