default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  template: template0
<% if ENV['POSTGRES_USER'].present? %>
  username: <%= ENV['POSTGRES_USER'] %>
<% end %>
<% if ENV['POSTGRES_PASSWORD'].present? %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
<% end %>
<% if ENV['POSTGRES_HOST'].present? %>
  host: <%= ENV['POSTGRES_HOST'] %>
<% end %>
<% if ENV['POSTGRES_PORT'].present? %>
  port: <%= ENV['POSTGRES_PORT'] %>
<% end %>

development: &development
  <<: *default
  database: unnote_development

test:
  <<: *default
  database: unnote_test

production:
  <<: *default
  database: unnote
  username: app

local_production:
  <<: *development
